# Generated by Django 4.2.16 on 2024-09-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('draft', models.BooleanField(default=False)),
            ],
        ),
    ]
