# Generated by Django 4.2.16 on 2024-09-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynotes',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
