# Generated by Django 4.2.16 on 2024-09-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_mynotes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynotes',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
