# Generated by Django 4.2.16 on 2024-10-05 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_mynotes_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyNotes',
            new_name='Note',
        ),
    ]
