# Generated by Django 4.2.16 on 2024-10-10 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_mynotes_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name_plural': 'Markdown Content'},
        ),
    ]
